;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/secondsbar]
type = custom/script
exec = ~/your_path/secondsbar.sh
interval = 1
format = <label>
label = %output%

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_